// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJHSvQbsqv3fDI_g0psKzpNIB4fLG0Tzg',
    appId: '1:650154917285:web:7aa38093c8bd3f3479fc4c',
    messagingSenderId: '650154917285',
    projectId: 'boxtancap',
    authDomain: 'boxtancap.firebaseapp.com',
    storageBucket: 'boxtancap.firebasestorage.app',
    measurementId: 'G-K7TSF05GTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQA5lXrCpSxpSpz2n24WVgQfkMRpyjbGk',
    appId: '1:650154917285:android:7ab9ee21823c247679fc4c',
    messagingSenderId: '650154917285',
    projectId: 'boxtancap',
    storageBucket: 'boxtancap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWprqkOV6ZHc8bER-YAzcmH6otjYV4uJ0',
    appId: '1:650154917285:ios:58843dad821adcb179fc4c',
    messagingSenderId: '650154917285',
    projectId: 'boxtancap',
    storageBucket: 'boxtancap.firebasestorage.app',
    iosBundleId: 'com.example.tugas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWprqkOV6ZHc8bER-YAzcmH6otjYV4uJ0',
    appId: '1:650154917285:ios:58843dad821adcb179fc4c',
    messagingSenderId: '650154917285',
    projectId: 'boxtancap',
    storageBucket: 'boxtancap.firebasestorage.app',
    iosBundleId: 'com.example.tugas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJHSvQbsqv3fDI_g0psKzpNIB4fLG0Tzg',
    appId: '1:650154917285:web:791407259f06086279fc4c',
    messagingSenderId: '650154917285',
    projectId: 'boxtancap',
    authDomain: 'boxtancap.firebaseapp.com',
    storageBucket: 'boxtancap.firebasestorage.app',
    measurementId: 'G-75BZ5B400C',
  );
}
